/*
 * Copyright (c) 2026 Olo Labs. All rights reserved.
 */

package org.olo.annotations;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Serializable parameter metadata for plugin JSON (variable mapping).
 * Generated by the annotation processor from {@link OloPluginParam}.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class PluginParamInfo {

    private final String name;
    private final String type;
    private final Boolean required;

    public PluginParamInfo(String name, String type, Boolean required) {
        this.name = name;
        this.type = type;
        this.required = required;
    }

    public String getName() { return name; }
    public String getType() { return type; }
    public Boolean getRequired() { return required; }
}
