/*
 * Copyright (c) 2026 Olo Labs. All rights reserved.
 */

package org.olo.annotations;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;

/**
 * Serializable plugin metadata for JSON generation. Used for drag-and-drop on canvas
 * and variable mapping: id, displayName, contractType, input/output parameters, etc.
 * Generated by the annotation processor from {@link OloPlugin}.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class PluginInfo {

    private final String id;
    private final String displayName;
    private final String contractType;
    private final String contractVersion;
    private final String description;
    private final String category;
    private final String icon;
    private final List<PluginParamInfo> inputParameters;
    private final List<PluginParamInfo> outputParameters;
    private final String className;

    public PluginInfo(
            String id,
            String displayName,
            String contractType,
            String contractVersion,
            String description,
            String category,
            String icon,
            List<PluginParamInfo> inputParameters,
            List<PluginParamInfo> outputParameters,
            String className) {
        this.id = id;
        this.displayName = displayName;
        this.contractType = contractType;
        this.contractVersion = contractVersion;
        this.description = description;
        this.category = category;
        this.icon = icon;
        this.inputParameters = inputParameters != null ? List.copyOf(inputParameters) : List.of();
        this.outputParameters = outputParameters != null ? List.copyOf(outputParameters) : List.of();
        this.className = className;
    }

    public String getId() { return id; }
    public String getDisplayName() { return displayName; }
    public String getContractType() { return contractType; }
    public String getContractVersion() { return contractVersion; }
    public String getDescription() { return description; }
    public String getCategory() { return category; }
    public String getIcon() { return icon; }
    public List<PluginParamInfo> getInputParameters() { return inputParameters; }
    public List<PluginParamInfo> getOutputParameters() { return outputParameters; }
    public String getClassName() { return className; }
}
