/*
 * Copyright (c) 2026 Olo Labs. All rights reserved.
 */

package org.olo.annotations;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Serializable UI component metadata for JSON generation and plug-and-play loading.
 * Generated by the annotation processor from {@link OloUiComponent}.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class UiComponentInfo {

    private final String id;
    private final String name;
    private final String category;
    private final String description;
    private final String icon;
    private final String className;

    public UiComponentInfo(String id, String name, String category, String description, String icon, String className) {
        this.id = id;
        this.name = name;
        this.category = category;
        this.description = description;
        this.icon = icon;
        this.className = className;
    }

    public String getId() { return id; }
    public String getName() { return name; }
    public String getCategory() { return category; }
    public String getDescription() { return description; }
    public String getIcon() { return icon; }
    public String getClassName() { return className; }
}
